### ISSUE TITLE
Use absolute paths derived from `sys.executable` in job script

### ISSUE THREAD

**Issue by dsroberts** [ACCESS-Community-Hub/ACCESS-MOPPeR#113]
This will ensure that when `mop` is run from a virtual env or some other conda environment it'll just work.

**Comment by paolap** [comment]
I'm not sure I fully understand this issue, to clarify:
is the job script  mopper_job.sh?
Because there we have 
"cd /g/data..." whatever the appdir passed into the configuration file is  
and then "mop -c config-file run" is launched from there.
Are you proposing to change this to
"mop -c <full-path to config file> run" ?

**Comment by dsroberts** [comment]
So I'm running mopper out of a virtual env, and the script it generates loads an analysis environment and then `mop -c config-file run`. This fails, as it doesn't pick up that `mop` came out of a virtual env. If we changed `mop` to something like `os.path.dirname(sys.executable) +'/mop'` would fix it.

**Comment by paolap** [comment]
ok, I get it, I was kind of assuming eventually it would be in hh5, which is actually wrong as it might be easier to actually have "your" own version installed. All of this how to call it execute and from where, how to handle the data properly is quite messy and unclear at the moment

**Comment by paolap** [comment]
It's now generating this for me:
 /g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/bin/mop which however it's not what I want as the mop I want to use is installed in .local 
It could also be problematic as it's not the module I'm loading automatically which is the latest stable. I'm not sure how to make this work for all sorts of different cases.
Ultimately if you run this with "test=true" in the config file you can modify mopper_job.sh before you run the script. 
We could potentially test if that executable exists and if not just passing mop. Or otherwise add something else to the config file which specify which "mop" to use.

I guess the possible scenarios are:
1) a user installs this on their own loading a conda env we supply which has all the dependencies and uses it from .local
2) we get this installed in hh5 envs which should be doable provided we manage the data correctly, some files will come with the package but in some cases you have to add/modify some input files
3) a user create a separate conda env, not sure if this is needed as it doesn't give you any advantage compared to option 1 or 2. I can see this useful only if eventually CMOR is not part anymore of shared conda envs

**Comment by paolap** [comment]
I've added an extra field in the config file called 
"conda_env"

a user can pass  a path relative to appdir or the absolute path for their custom conda env activate command
conda_env: mopper-env/bin/activate

The code will add a line

"source <appdir>/<conda-env>" to the job file so this env can be used.

There are still a couple of assumptions here, 

1) module load conda/analysis3-unstable
   is the default behavior (hopefully we will have mopper there soon)
2) the user env is also built on top of conda/analysis3-unstable or at least they are both loaded

WE could customise this further or better but for the moment should be enough. If the setup is run with the "test: true" option then a user can always sort out the modules before submitting the job
