### ISSUE TITLE
Variables not working

### ISSUE THREAD

**Issue by greensh16** [ACCESS-Community-Hub/ACCESS-MOPPeR#127]
Ocean Monthly:

- [ ] hfds - Error: variable: hfds, cmor and user units are incompatible: W m-2 and m/sec for variable hfds (table: Omon)
- [ ] msftmrho - Error: variable: msftmrho, cmor and user units are incompatible: kg s-1 and kg/m^3 for variable msftmrho (table: Omon)
- [ ] msftmz - Error: variable: msftmz, cmor and user units are incompatible: kg s-1 and m/sec for variable msftmz (table: Omon)

**Comment by paolap** [comment]
Uhm to fix these I need to overwrite the units passed by the files, if you notice the actual mappings have the correct units, look in /mappings/map_ocean_OM2.csv

I'll see if this is doable, I thought actually I was already doing it otherwise you can fix it manually for the moment, i.e. pick the cmor units . In fact all the units are somehow bad as they should write them m s_1 instead of m/s . Can you tell me where your mappings file is so I see if this happens only for derived variables or for all of them

**Comment by greensh16** [comment]
/g/data/hh5/tmp/sg7549/ACCESS/ACCESS-MOPPeR_latest/seb_working/map_ocean_month.csv

**Comment by paolap** [comment]
I've added a units check before writing data to template file, I was already doing that for realm, so I adapt check_realm() to check_realm_units(). Still have to test if it works

**Comment by paolap** [comment]
This fix works

**Comment by paolap** [comment]
adding also that I removed bug happening when find_matches() was trying to match 'realm' exactly to the realm in cmor table. This sometimes has a list of realms so now is trying to split realm from table and see if realm from mapping is in it.
