### ISSUE TITLE
Missing `tstep_delta.yaml` in mopdata

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Community-Hub/ACCESS-MOPPeR#195]
Hi @paolap 

I am hitting that error

```
Found experiment: di787
Check that /g/data/xp65/public/apps/med_conda/envs/access-med-0.7/lib/python3.10/site-packages/mopdata/tstep_delta.yaml exists and it is a valid yaml file
ERROR: [Errno 2] No such file or directory: '/g/data/xp65/public/apps/med_conda/envs/access-med-0.7/lib/python3.10/site-packages/mopdata/tstep_delta.yaml'
```

`tstep_delta.yaml` is missing in the repo.

**Comment by paolap** [comment]
I already noticed that, and I fixed it by releasing a new conda package (v1.1.1) with the file, unfortunately analysis3 install is failing because of other packages. Trying to work out right now which test I need to skip. You can always use the new conda package from the coecms conda channel

**Comment by rbeucher** [comment]
It's not in the source repo.

**Comment by paolap** [comment]
dang! Can't see why it doesn't like this file, will try again but if you just create your own env like suggested in the docs you should get away by just adding the file manually if it's not there

**Comment by rbeucher** [comment]
Sure. I'll wait for the file

**Comment by paolap** [comment]
So the file is in main, I've re-created the conda package and will have another go at fixing the tests in analysis3. This might take a while, I'm not sure if I identified the right issue, it has nothing to do with mopper. You can wait or use the new conda  package. It's still version 1.1.1 as it turns out I forgot to publish the DOI, so I was able to just reuse the same tag.

**Comment by rbeucher** [comment]
Thanks!

**Comment by paolap** [comment]
Finally new version in analysis3-unstable, I'm not getting anymore the error
